version: "3"

services:
  backend:
    build: backend
    restart: unless-stopped
    environment:
      - PORT=8000
      - MAX_WORKERS=10
    ports:
      - "8000:8000"
    expose:
      - 8000
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --workers $${MAX_WORKERS}"

  frontend:
    build: frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend
